// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vtewjrneoxviyqippfph.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ0ZXdqcm5lb3h2aXlxaXBwZnBoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyOTYwMTksImV4cCI6MjA2OTg3MjAxOX0.kDcmJnaZrtEpV3IEM4GeSjVZbE1xe4aMD1DPF49fqpk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});